### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by wsdjeg**
the constructor of UserReposClient is UserReposClient(android.content.Context),UserReposClient(android.content.Context,String),UserReposClient(android.content.Context,int);
there is not UserReposClient(Activity,String);

### CODE REVIEW

**Comment by alorma** [comment]
That doesn't make sense.

getActivity() provides activity, and Activity is already Context

**Comment by wsdjeg** [comment]
i know but the compile checker show me the error
can not find the method getActivity(),maybe it is due to i am using v7

**Comment by wsdjeg** [comment]
i have remove the unnecessary change

**Comment by wsdjeg** [comment]
the method of AppCompatActivity is getBaseContext()

**Comment by alorma** [comment]
of course, the getActivity is used in fragments, but i guess users will understand that

**Comment by wsdjeg** [comment]
i think so

**Pull request merged**
