### PR TITLE
Create chrome

### PR DESCRIPTION
**Pull request by yuanyaoge**
Google chrome

### CODE REVIEW

**Comment by alorma** [comment]
????

**Comment by paulkramme** [comment]
Closed as not contructive.

**Comment by GeorgeWL** [comment]
@paulkramme and @alorma 

This kind of  thing seems to be happening all over github, I think it's spambots.

The best option is to just kill the pull and report the users.

>Spammy Behaviour.
>Creating Empty pull requests in multiple repositories.

The Github Moderators should hopefully stop them straight after that. If you look on the user logs they're both doing the exact same thing on multiple repositories.

**Comment by alorma** [comment]
Thanks @georgewl

**Pull request closed without merging**
