### PR TITLE
Changes for PocketHub

### PR DESCRIPTION
**Pull request by Meisolsson**
All the changes we need for PocketHub to change SDK. Most of it has been tested.

If there's something you want me to change just tell me!

### CODE REVIEW

**Comment by alorma** [comment]
What is GollumPage?

**Comment by alorma** [comment]
I will upload a new version of aar tomorrow.

**Comment by Meisolsson** [comment]
GollumPage is the updated wiki page from a GollumEvent

**Comment by alorma** [comment]
And what is GollumEvent? Never heard about it

**Comment by Meisolsson** [comment]
It’s an event for wiki updates.
> 27 aug 2015 kl. 08:26 skrev Bernat Borrás Paronella <notifications@github.com>:
> 
> And what is GollumEvent? Never heard about it
>

**Comment by Meisolsson** [comment]
Before updating change my typo! In MemberEventPayload i misspelled the object "member" as "memeber"

**Comment by alorma** [comment]
Can you make another PR?

**Pull request merged**
