### PR TITLE
Enable standalone builds

### PR DESCRIPTION
**Pull request by larsgrefer**
Modify the ```build.gradle``` and add the gradle-wrapper in order to enable standalone builds of the library

If this is merged i'll provide travis (http://travis-ci.org) support in a second pull-request

### CODE REVIEW

**Comment by alorma** [comment]
Did you used the development branch as a base?

**Comment by larsgrefer** [comment]
no, this just adds one commit to master

**Comment by alorma** [comment]
Uhmmm, i'm modifying the SDK, to use a BaseSDK, i will add this PR once i
do that

**Comment by larsgrefer** [comment]
I'm just trying to add this to the develop branch, but it does not compile because of:
```
> Could not find property 'GH_DEV_ID'
```
and
```
> Project with path ':sdks:BaseSDK' could not be found in root project 'github-android-sdk'.
```

**Comment by alorma** [comment]
Yes i know.

You need to modify the gradle.properties for GH_DEV_ID, but now this SDK
contains a dependency from a module that it's only in... GitSkarios main
Repo!

I know this is bad, and i will try to fix it asap

**Comment by larsgrefer** [comment]
You should consider managing the dependencies via maven (jcenter)

Especially if you want to provide the SDK as described in forkhubs/android#792

**Comment by alorma** [comment]
Yeah i know, it's something i want to do... sometime.

**Comment by alorma** [comment]
We finally moved to create a Maven suport throug jCenter

**Pull request closed without merging**
